name: NASA Project CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    env: 
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    strategy: 
      matrix: 
        node-version: [17.x, 18.x]
        mongodb-version: ['6.0']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Updated to v2
        with:
          repository: khaledelhannat/nasa-control-mission
          ref: main
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm run install-all
      - run: npm run build-react-unix
      - run: npm run test-all
